title: Open Source
author: Chibomia
email: info@chibomia.ca
description: > # this means to ignore newlines until "baseurl:"
  More to come

# social links
twitter_username: your-twitter-handle
github_username:  lboz

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
